### ISSUE TITLE
Amino Acid not in Alphabet

### ISSUE THREAD

**Issue by SophieS9** [ntranoslab/esm-variants#6]
Hi Team - thanks for the great piece of software! 

I've hit an issue where prediction is failing on the fasta file from the gene SELENON (attached, changed to .txt to allow upload - [protein.txt](https://github.com/ntranoslab/esm-variants/files/12685074/protein.txt)). From the error trace below, I think it's because it doesn't like the "U" in the sequence, but this is the amino acid code for selenocysteine. 
```
Traceback (most recent call last):
  File "/home/sophieshaw/esm-variants/esm_score_missense_mutations.py", line 77, in <module>
    main(args)
  File "/home/sophieshaw/esm-variants/esm_score_missense_mutations.py", line 51, in main
    input_df_ids, LLRs = get_wt_LLR(input_df, model=model, alphabet=alphabet, batch_converter=batch_converter, d
  File "/home/sophieshaw/esm-variants/esm_variants_utils.py", line 38, in get_wt_LLR
    wt_norm=np.diag(WTlogits.loc[[i.split(' ')[0] for i in WTlogits.columns]])
  File "/home/sophieshaw/miniconda3/envs/pm1_automation/lib/python3.7/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/sophieshaw/miniconda3/envs/pm1_automation/lib/python3.7/site-packages/pandas/core/indexing.py", line 1153, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/sophieshaw/miniconda3/envs/pm1_automation/lib/python3.7/site-packages/pandas/core/indexing.py", line 1093, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/sophieshaw/miniconda3/envs/pm1_automation/lib/python3.7/site-packages/pandas/core/indexing.py", line 1314, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis)
  File "/home/sophieshaw/miniconda3/envs/pm1_automation/lib/python3.7/site-packages/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: "['U'] not in index"

```

Any suggestions?

Thanks!

Sophie S

**Comment by nadavbra** [comment]
Our code currently doesn't handle non-standard amino acids. I'm currently in the process of refactoring some of our code, and this will be trivial to fix after the refactor, but it may take a few weeks until I get to it. Sorry about that.

**Comment by SophieS9** [comment]
No problem :) Thanks for the update @nadavbra!

**Comment by zachary-cyl** [comment]
> Our code currently doesn't handle non-standard amino acids. I'm currently in the process of refactoring some of our code, and this will be trivial to fix after the refactor, but it may take a few weeks until I get to it. Sorry about that.

Hi, just checking in—has the issue with handling non-standard amino acids been resolved yet? Thanks!

**Comment by zachary-cyl** [comment]
> Our code currently doesn't handle non-standard amino acids. I'm currently in the process of refactoring some of our code, and this will be trivial to fix after the refactor, but it may take a few weeks until I get to it. Sorry about that.

Hi, has the issue with handling non-standard amino acids been resolved yet?   Thanks!

**Comment by nadavbra** [comment]
@zachary-cyl I really apologize that we haven't got to it yet. I recently started a new job and had to put the refactoring project on hold. I still believe it would be relatively easy to fix this issue even without the refactoring, but I haven't got to it yet. 
If you want to try modifying the code, it should be relatively simple (you can ask ChatGPT to help you). It's important to test and ensure backward compatibility (that you get the same scores for standard amino acids as in the existing framework). If you want to do that and make a pull request, I'd be happy to go over your code changes.
